version: '3.7'

services:
  product_service:
    build: ./product-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./product-service/:/app/
    ports:
      - 8081:8000
    environment:
      - DATABASE_URI=postgresql://product_db_username:product_db_password@product_db/product_db_dev
      - USER_SERVICE_HOST_URL=http://user_service:8000/api/v1/users/
    depends_on:
      - product_db

  product_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_product:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=product_db_username
      - POSTGRES_PASSWORD=product_db_password
      - POSTGRES_DB=product_db_dev

  user_service:
    build: ./user-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./user-service/:/app/
    ports:
      - 8082:8000
    environment:
      - DATABASE_URI=postgresql://user_db_username:user_db_password@user_db/user_db_dev
    depends_on:
      - user_db

  user_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_db_username
      - POSTGRES_PASSWORD=user_db_password
      - POSTGRES_DB=user_db_dev
  
  order_service:
    build: ./order-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./order-service/:/app/
    ports:
      - 8083:8000
    environment:
      - DATABASE_URI=postgresql://order_db_username:order_db_password@order_db/order_db_dev
      - USER_SERVICE_HOST_URL=http://user_service:8000/api/v1/users/
      - PRODUCT_SERVICE_HOST_URL=http://product_service:8000/api/v1/products/
    depends_on:
      - order_db

  order_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_order:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=order_db_username
      - POSTGRES_PASSWORD=order_db_password
      - POSTGRES_DB=order_db_dev

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - product_service
      - user_service
      - order_service

volumes:
  pgadmin-data:
  postgres_data_product:
  postgres_data_user:
  postgres_data_order: